// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: hc01_v9.2

#ifndef UI_COMMON_H
#define UI_COMMON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    typedef struct device
    {
        char name[128]; // TB device description
        uint32_t type;
    } device_t;

    extern lv_obj_t *ui_devices_light(lv_obj_t *root, device_t *dev);
    extern lv_obj_t *ui_devices_row(lv_obj_t *root, device_t *dev1, device_t *dev2);
    extern lv_obj_t *ui_points(lv_obj_t *root, int num_point, int index);
    extern lv_obj_t *ui_device_light(device_t *dev);
    extern lv_obj_t *ui_device_switch_rgb_1(device_t *dev);
    extern lv_obj_t *ui_device_switch_rgb_2(device_t *dev);
    extern lv_obj_t *ui_device_switch_rgb_3(device_t *dev);
    extern lv_obj_t *ui_device_switch_rgb_4(device_t *dev);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
