// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: hc01_v9.2

#include "ui_common.h"
// #include "font_awesome.h"
#include "font_puhui.h"

lv_obj_t *ui_devices_light(lv_obj_t *root, device_t *dev)
{
    if (root)
    {
        lv_obj_t *ui_dev = lv_button_create(root);
        lv_obj_set_width(ui_dev, 220);
        lv_obj_set_height(ui_dev, 140);
        lv_obj_set_align(ui_dev, LV_ALIGN_CENTER);
        lv_obj_add_flag(ui_dev, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
        lv_obj_remove_flag(ui_dev, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
        lv_obj_set_style_bg_color(ui_dev, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_dev, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

        lv_obj_t *ui_devIcon = lv_image_create(ui_dev);
        if (dev->type == 1)
            lv_image_set_src(ui_devIcon, &ui_img_light_png);
        else
            lv_image_set_src(ui_devIcon, &ui_img_lamp_png);
        lv_obj_set_width(ui_devIcon, LV_SIZE_CONTENT);          /// 1
        lv_obj_set_height(ui_devIcon, LV_SIZE_CONTENT);         /// 1
        lv_obj_add_flag(ui_devIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
        lv_obj_remove_flag(ui_devIcon, LV_OBJ_FLAG_SCROLLABLE); /// Flags

        lv_obj_t *ui_onoffBt = lv_button_create(ui_dev);
        lv_obj_set_width(ui_onoffBt, 70);
        lv_obj_set_height(ui_onoffBt, 70);
        lv_obj_set_align(ui_onoffBt, LV_ALIGN_TOP_RIGHT);
        lv_obj_add_flag(ui_onoffBt, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
        lv_obj_remove_flag(ui_onoffBt, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
        lv_obj_set_style_border_side(ui_onoffBt, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

        lv_obj_t *ui_devName = lv_label_create(ui_dev);
        lv_obj_set_width(ui_devName, LV_SIZE_CONTENT);  /// 1
        lv_obj_set_height(ui_devName, LV_SIZE_CONTENT); /// 1
        lv_obj_set_align(ui_devName, LV_ALIGN_BOTTOM_LEFT);
        lv_label_set_text(ui_devName, dev->name);
        lv_obj_set_style_text_font(ui_devName, &font_puhui_basic_20_4, LV_PART_MAIN | LV_STATE_DEFAULT);

        lv_obj_set_user_data(ui_onoffBt, dev);
        lv_obj_add_event_cb(ui_onoffBt, ui_event_onoffBt, LV_EVENT_ALL, NULL);

        lv_obj_set_user_data(ui_dev, dev);
        lv_obj_add_event_cb(ui_dev, ui_event_dev, LV_EVENT_ALL, NULL);

        return ui_dev;
    }
    return NULL;
}

lv_obj_t *ui_devices_row(lv_obj_t *root, device_t *dev1, device_t *dev2)
{
    if (root)
    {
        lv_obj_t *ui_devRow = lv_obj_create(root);
        lv_obj_remove_style_all(ui_devRow);
        lv_obj_set_width(ui_devRow, 480);
        lv_obj_set_height(ui_devRow, 150);
        lv_obj_set_align(ui_devRow, LV_ALIGN_CENTER);
        lv_obj_set_flex_flow(ui_devRow, LV_FLEX_FLOW_ROW);
        lv_obj_set_flex_align(ui_devRow, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_remove_flag(ui_devRow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

        if (dev1)
            ui_devices_light(ui_devRow, dev1);
        if (dev2)
            ui_devices_light(ui_devRow, dev2);
        return ui_devRow;
    }
    return NULL;
}

lv_obj_t *ui_points(lv_obj_t *root, int num_point, int index)
{
    if (root)
    {
        lv_obj_t *points = lv_obj_create(root);
        lv_obj_remove_style_all(points);
        lv_obj_set_width(points, 250);
        lv_obj_set_height(points, 20);
        lv_obj_set_x(points, 0);
        lv_obj_set_y(points, -10);
        lv_obj_set_align(points, LV_ALIGN_BOTTOM_MID);
        lv_obj_set_flex_flow(points, LV_FLEX_FLOW_ROW);
        lv_obj_set_flex_align(points, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_remove_flag(points, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

        lv_obj_t *ui_point = NULL;
        for (int i = 0; i < num_point; i++)
        {
            if (i == index - 1)
            {
                ui_point = lv_obj_create(points);
                lv_obj_remove_style_all(ui_point);
                lv_obj_set_width(ui_point, 10);
                lv_obj_set_height(ui_point, 10);
                lv_obj_set_align(ui_point, LV_ALIGN_CENTER);
                lv_obj_remove_flag(ui_point, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
                lv_obj_set_style_radius(ui_point, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
                lv_obj_set_style_bg_color(ui_point, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                lv_obj_set_style_bg_opa(ui_point, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            }
            else
            {
                ui_point = lv_obj_create(points);
                lv_obj_remove_style_all(ui_point);
                lv_obj_set_width(ui_point, 6);
                lv_obj_set_height(ui_point, 6);
                lv_obj_set_align(ui_point, LV_ALIGN_CENTER);
                lv_obj_remove_flag(ui_point, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
                lv_obj_set_style_radius(ui_point, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
                lv_obj_set_style_bg_color(ui_point, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
                lv_obj_set_style_bg_opa(ui_point, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            }
        }
        return points;
    }
    return NULL;
}
