// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: hc01_v9.2

#include "../ui.h"
#include "ui_common.h"

lv_obj_t *ui_devices = NULL;
lv_obj_t *ui_devList = NULL;

// event funtions
void ui_event_devices(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT)
    {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home_screen_init);
    }
}

void ui_event_dev(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        detail_dev(e);
    }
}

void ui_event_onoffBt(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        turn_on_dev(e);
    }
}

void ui_event_dev2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        detail_dev(e);
    }
}

void ui_event_onoffBt2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        turn_on_dev(e);
    }
}

// build funtions

device_t devices[20] = {
    {"Thiết bị 1", 1},
    {"Thiết bị 2", 1},
    {"Thiết bị 3", 2},
    {"Thiết bị 4", 2},
    {"Thiết bị 5", 1},
    {"Thiết bị 6", 2},
    {"Thiết bị 7", 2},
    {"Thiết bị 8", 1},
    {"Thiết bị 9", 1},
    {"Thiết bị 10", 2},
    {"Thiết bị 11", 2},
    {"Thiết bị 12", 2},
    {"Thiết bị 13", 1},
    {"Thiết bị 14", 1},
    {"Thiết bị 15", 1},
    {"Thiết bị 16", 1},
    {"Thiết bị 17", 1},
    {"Thiết bị 18", 1},
    {"Thiết bị 19", 1},
    {"Thiết bị 20", 1},
};

// build funtions

void ui_devices_screen_init(void)
{
    ui_devices = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_devices, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_devices, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_devices, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devList = lv_obj_create(ui_devices);
    lv_obj_remove_style_all(ui_devList);
    lv_obj_set_width(ui_devList, 480);
    lv_obj_set_height(ui_devList, 480);
    lv_obj_set_align(ui_devList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_devList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_devList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_devList, LV_OBJ_FLAG_CLICKABLE); /// Flags
    lv_obj_set_scroll_dir(ui_devList, LV_DIR_VER);

    int num_dev = 20;
    for (int i = 0; i < num_dev / 2; i++)
    {
        lv_obj_t *ui_devRow = ui_devices_row(ui_devList, &devices[2 * i], &devices[2 * i + 1]);
    }

    ui_points(ui_devices, 2, 2);

    lv_obj_add_event_cb(ui_devices, ui_event_devices, LV_EVENT_ALL, NULL);
}

void ui_devices_screen_destroy(void)
{
    if (ui_devices)
        lv_obj_del(ui_devices);

    // NULL screen variables
    ui_devices = NULL;
    ui_devList = NULL;
}
