// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: hc01_v9.2

#ifndef UI_DEVICES_H
#define UI_DEVICES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_devices
extern void ui_devices_screen_init(void);
extern void ui_devices_screen_destroy(void);
extern void ui_event_devices(lv_event_t * e);
extern lv_obj_t * ui_devices;
extern lv_obj_t * ui_devList;

extern void ui_event_dev(lv_event_t * e);
extern void ui_event_onoffBt(lv_event_t * e);
extern void ui_event_dev2(lv_event_t * e);
extern void ui_event_onoffBt2(lv_event_t * e);
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
