// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: hc01_v9.2

#include "../ui.h"

lv_obj_t * ui_home = NULL;
lv_obj_t * ui_clockAndWeather = NULL;
lv_obj_t * ui_clock = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_day = NULL;
lv_obj_t * ui_weather = NULL;
lv_obj_t * ui_weatherIcon = NULL;
lv_obj_t * ui_relayRow1 = NULL;
lv_obj_t * ui_dev3 = NULL;
lv_obj_t * ui_devIcon3 = NULL;
lv_obj_t * ui_onoffBt3 = NULL;
lv_obj_t * ui_devName3 = NULL;
lv_obj_t * ui_dev5 = NULL;
lv_obj_t * ui_devIcon5 = NULL;
lv_obj_t * ui_onoffBt5 = NULL;
lv_obj_t * ui_devName5 = NULL;
lv_obj_t * ui_relayRow2 = NULL;
lv_obj_t * ui_dev6 = NULL;
lv_obj_t * ui_devIcon6 = NULL;
lv_obj_t * ui_onoffBt6 = NULL;
lv_obj_t * ui_devName6 = NULL;
lv_obj_t * ui_dev7 = NULL;
lv_obj_t * ui_devIcon7 = NULL;
lv_obj_t * ui_onoffBt7 = NULL;
lv_obj_t * ui_devName7 = NULL;
lv_obj_t * ui_point = NULL;
lv_obj_t * ui_point1 = NULL;
lv_obj_t * ui_point2 = NULL;
// event funtions
void ui_event_home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_devices, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_devices_screen_init);
    }
}

// build funtions

void ui_home_screen_init(void)
{
    ui_home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_home, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockAndWeather = lv_obj_create(ui_home);
    lv_obj_remove_style_all(ui_clockAndWeather);
    lv_obj_set_width(ui_clockAndWeather, 480);
    lv_obj_set_height(ui_clockAndWeather, 150);
    lv_obj_set_align(ui_clockAndWeather, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_clockAndWeather, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_clockAndWeather, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clockAndWeather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clock = lv_obj_create(ui_clockAndWeather);
    lv_obj_remove_style_all(ui_clock);
    lv_obj_set_width(ui_clock, 220);
    lv_obj_set_height(ui_clock, 140);
    lv_obj_set_align(ui_clock, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_clock, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_clock, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_clock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_clock);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_time, "08 : 16");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_clock);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_day, "May 25 Tue");
    lv_obj_set_style_text_color(ui_day, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_obj_create(ui_clockAndWeather);
    lv_obj_remove_style_all(ui_weather);
    lv_obj_set_width(ui_weather, 220);
    lv_obj_set_height(ui_weather, 140);
    lv_obj_set_align(ui_weather, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_weather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weatherIcon = lv_image_create(ui_weather);
    lv_image_set_src(ui_weatherIcon, &ui_img_rainy_png);
    lv_obj_set_width(ui_weatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weatherIcon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_weatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_weatherIcon, 20);

    ui_relayRow1 = lv_obj_create(ui_home);
    lv_obj_remove_style_all(ui_relayRow1);
    lv_obj_set_width(ui_relayRow1, 480);
    lv_obj_set_height(ui_relayRow1, 150);
    lv_obj_set_x(ui_relayRow1, 0);
    lv_obj_set_y(ui_relayRow1, 150);
    lv_obj_set_align(ui_relayRow1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_relayRow1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_relayRow1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_relayRow1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dev3 = lv_button_create(ui_relayRow1);
    lv_obj_set_width(ui_dev3, 220);
    lv_obj_set_height(ui_dev3, 140);
    lv_obj_set_align(ui_dev3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dev3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_dev3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dev3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dev3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devIcon3 = lv_image_create(ui_dev3);
    lv_image_set_src(ui_devIcon3, &ui_img_light_png);
    lv_obj_set_width(ui_devIcon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devIcon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_remove_flag(ui_devIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onoffBt3 = lv_button_create(ui_dev3);
    lv_obj_set_width(ui_onoffBt3, 70);
    lv_obj_set_height(ui_onoffBt3, 70);
    lv_obj_set_align(ui_onoffBt3, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_onoffBt3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_onoffBt3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_onoffBt3, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_onoffBt3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devName3 = lv_label_create(ui_dev3);
    lv_obj_set_width(ui_devName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_devName3, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_devName3, "Tên thiết bị");
    lv_obj_set_style_text_font(ui_devName3, &font_puhui_basic_20_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dev5 = lv_button_create(ui_relayRow1);
    lv_obj_set_width(ui_dev5, 220);
    lv_obj_set_height(ui_dev5, 140);
    lv_obj_set_align(ui_dev5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dev5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_dev5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dev5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dev5, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devIcon5 = lv_image_create(ui_dev5);
    lv_image_set_src(ui_devIcon5, &ui_img_lamp_png);
    lv_obj_set_width(ui_devIcon5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devIcon5, LV_SIZE_CONTENT);    /// 1
    lv_obj_remove_flag(ui_devIcon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onoffBt5 = lv_button_create(ui_dev5);
    lv_obj_set_width(ui_onoffBt5, 70);
    lv_obj_set_height(ui_onoffBt5, 70);
    lv_obj_set_align(ui_onoffBt5, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_onoffBt5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_onoffBt5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_onoffBt5, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_onoffBt5, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devName5 = lv_label_create(ui_dev5);
    lv_obj_set_width(ui_devName5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devName5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_devName5, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_devName5, "Tên thiết bị");
    lv_obj_set_style_text_font(ui_devName5, &font_puhui_basic_20_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_relayRow2 = lv_obj_create(ui_home);
    lv_obj_remove_style_all(ui_relayRow2);
    lv_obj_set_width(ui_relayRow2, 480);
    lv_obj_set_height(ui_relayRow2, 150);
    lv_obj_set_x(ui_relayRow2, 0);
    lv_obj_set_y(ui_relayRow2, 300);
    lv_obj_set_align(ui_relayRow2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_relayRow2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_relayRow2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_relayRow2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dev6 = lv_button_create(ui_relayRow2);
    lv_obj_set_width(ui_dev6, 220);
    lv_obj_set_height(ui_dev6, 140);
    lv_obj_set_align(ui_dev6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dev6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_dev6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dev6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dev6, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devIcon6 = lv_image_create(ui_dev6);
    lv_image_set_src(ui_devIcon6, &ui_img_light_png);
    lv_obj_set_width(ui_devIcon6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devIcon6, LV_SIZE_CONTENT);    /// 1
    lv_obj_remove_flag(ui_devIcon6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onoffBt6 = lv_button_create(ui_dev6);
    lv_obj_set_width(ui_onoffBt6, 70);
    lv_obj_set_height(ui_onoffBt6, 70);
    lv_obj_set_align(ui_onoffBt6, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_onoffBt6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_onoffBt6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_onoffBt6, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_onoffBt6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devName6 = lv_label_create(ui_dev6);
    lv_obj_set_width(ui_devName6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devName6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_devName6, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_devName6, "Tên thiết bị");
    lv_obj_set_style_text_font(ui_devName6, &font_puhui_basic_20_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dev7 = lv_button_create(ui_relayRow2);
    lv_obj_set_width(ui_dev7, 220);
    lv_obj_set_height(ui_dev7, 140);
    lv_obj_set_align(ui_dev7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dev7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_dev7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dev7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dev7, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devIcon7 = lv_image_create(ui_dev7);
    lv_image_set_src(ui_devIcon7, &ui_img_lamp_png);
    lv_obj_set_width(ui_devIcon7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devIcon7, LV_SIZE_CONTENT);    /// 1
    lv_obj_remove_flag(ui_devIcon7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onoffBt7 = lv_button_create(ui_dev7);
    lv_obj_set_width(ui_onoffBt7, 70);
    lv_obj_set_height(ui_onoffBt7, 70);
    lv_obj_set_align(ui_onoffBt7, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_onoffBt7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_onoffBt7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_onoffBt7, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_onoffBt7, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devName7 = lv_label_create(ui_dev7);
    lv_obj_set_width(ui_devName7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devName7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_devName7, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_devName7, "Tên thiết bị");
    lv_obj_set_style_text_font(ui_devName7, &font_puhui_basic_20_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_point = lv_obj_create(ui_home);
    lv_obj_remove_style_all(ui_point);
    lv_obj_set_width(ui_point, 50);
    lv_obj_set_height(ui_point, 20);
    lv_obj_set_x(ui_point, 0);
    lv_obj_set_y(ui_point, -10);
    lv_obj_set_align(ui_point, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_point, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_point, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_point, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_point1 = lv_obj_create(ui_point);
    lv_obj_remove_style_all(ui_point1);
    lv_obj_set_width(ui_point1, 10);
    lv_obj_set_height(ui_point1, 10);
    lv_obj_set_align(ui_point1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_point1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_point1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_point1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_point1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_point2 = lv_obj_create(ui_point);
    lv_obj_remove_style_all(ui_point2);
    lv_obj_set_width(ui_point2, 6);
    lv_obj_set_height(ui_point2, 6);
    lv_obj_set_align(ui_point2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_point2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_point2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_point2, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_point2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_home, ui_event_home, LV_EVENT_ALL, NULL);

}

void ui_home_screen_destroy(void)
{
    if(ui_home) lv_obj_del(ui_home);

    // NULL screen variables
    ui_home = NULL;
    ui_clockAndWeather = NULL;
    ui_clock = NULL;
    ui_time = NULL;
    ui_day = NULL;
    ui_weather = NULL;
    ui_weatherIcon = NULL;
    ui_relayRow1 = NULL;
    ui_dev3 = NULL;
    ui_devIcon3 = NULL;
    ui_onoffBt3 = NULL;
    ui_devName3 = NULL;
    ui_dev5 = NULL;
    ui_devIcon5 = NULL;
    ui_onoffBt5 = NULL;
    ui_devName5 = NULL;
    ui_relayRow2 = NULL;
    ui_dev6 = NULL;
    ui_devIcon6 = NULL;
    ui_onoffBt6 = NULL;
    ui_devName6 = NULL;
    ui_dev7 = NULL;
    ui_devIcon7 = NULL;
    ui_onoffBt7 = NULL;
    ui_devName7 = NULL;
    ui_point = NULL;
    ui_point1 = NULL;
    ui_point2 = NULL;

}
