// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: hc01_v9.2

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern void ui_event_home(lv_event_t * e);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_clockAndWeather;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_weatherIcon;
extern lv_obj_t * ui_relayRow1;
extern lv_obj_t * ui_dev3;
extern lv_obj_t * ui_devIcon3;
extern lv_obj_t * ui_onoffBt3;
extern lv_obj_t * ui_devName3;
extern lv_obj_t * ui_dev5;
extern lv_obj_t * ui_devIcon5;
extern lv_obj_t * ui_onoffBt5;
extern lv_obj_t * ui_devName5;
extern lv_obj_t * ui_relayRow2;
extern lv_obj_t * ui_dev6;
extern lv_obj_t * ui_devIcon6;
extern lv_obj_t * ui_onoffBt6;
extern lv_obj_t * ui_devName6;
extern lv_obj_t * ui_dev7;
extern lv_obj_t * ui_devIcon7;
extern lv_obj_t * ui_onoffBt7;
extern lv_obj_t * ui_devName7;
extern lv_obj_t * ui_point;
extern lv_obj_t * ui_point1;
extern lv_obj_t * ui_point2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

