// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: hc01_v9.2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void detail_dev(lv_event_t * e);
void turn_on_dev(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
