// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: hc01_v9.2

#include "ui.h"
#include <stdio.h>

typedef struct device
{
    char name[128]; // TB device description
    uint32_t type;
} device_t;

void detail_dev(lv_event_t *e)
{
    // Your code here
    lv_obj_t *btn = lv_event_get_target(e);
    device_t *u = lv_obj_get_user_data(btn);

    printf("detail_dev name = %s\n", u->name);
}

void turn_on_dev(lv_event_t *e)
{
    // Your code here
    lv_obj_t *btn = lv_event_get_target(e);
    device_t *u = lv_obj_get_user_data(btn);

    printf("turn_on_dev name = %s\n", u->name);
}
